[package]
name = "evm"
version = "0.1.0"
license = "Apache-2.0"
keywords = ["no_std", "ethereum"]
edition = "2021"

[dependencies]
log = { version = "0.4", default-features = false }
evm-core = { version = "0.35", path = "core", default-features = false }
evm-gasometer = { version = "0.35", path = "gasometer", default-features = false }
evm-runtime = { version = "0.35", path = "runtime", default-features = false }
sha3 = { version = "0.10", default-features = false }
rlp = { version = "0.5", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.0", default-features = false, features = ["derive"], optional = true }
ethereum = { version = "0.12", default-features = false }
environmental = { version = "1.1.2", default-features = false, optional = true }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"], optional = true }
auto_impl = "0.5.0"
kp-core = { path = "../primitives/core"}
kp-types = { path = "../primitives/types"}
kp-state = { path = "../primitives/state"}
[dev-dependencies]
criterion = "0.3"
hex = "0.4"

[[bench]]
name = "loop"
harness = false

[features]
default = ["std"]
with-codec = ["codec", "scale-info", "evm-core/with-codec", "ethereum/with-codec"]
with-serde = ["serde", "evm-core/with-serde", "ethereum/with-serde"]
std = ["evm-core/std", "evm-gasometer/std", "evm-runtime/std", "sha3/std", "kp-core/std", "serde/std", "codec/std", "log/std", "ethereum/std", "environmental/std", "scale-info/std"]
tracing = [
  "environmental",
  "evm-gasometer/tracing",
  "evm-runtime/tracing"
]