[package]
name = "evm-runtime"
version = "0.35.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
evm-core = { version = "0.35", path = "../core", default-features = false }
kp-core = { path = "../../primitives/core"}
sha3 = { version = "0.10", default-features = false }
environmental = { version = "1.1.2", default-features = false, optional = true}
auto_impl = "0.5.0"

[features]
default = ["std"]
std = ["evm-core/std", "kp-core/std", "sha3/std", "environmental/std"]
tracing = [
  "environmental"
]
